* My Emacs Init

This repo contains my init file for Emacs.

It was never intended to be published, so it is not organized and/or contains
necessarily quality code, but hopefully it will help someone someday.

Core princple: *Hydras are awesome*

** Setting up

   First, ensure your =~/.emacs= reads the init file:

#+begin_src elisp
;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
;; (package-initialize)
(load-file "<path-to-emacs-init.el>")
#+end_src

   Secondly, some variables can be customized. Those are described in
   the very top of =emacs-init.el=. We will look for a file in
   =~/.config/emacs_init/config.el=, load it and trust it to set the
   variables it needs to set. You can use this to have
   computer-specific settings, and to setup some vars needed for the
   emacs-init itself.

#+begin_src elisp
;; file: ~/.config/emacs_init/config.el
(custom-set-variables
 '(my-font-size "11")
 '(my-font-name "Hack"))
#+end_src

** Hooks

   You con put extra initiatilization logic on =~/.config/emacs_init/hook.el=. This
   file will be loaded at the very end of `emacs-init.el`.

** Modules

   The ~modules~ folder defines setups for languages/programs that we don't load
   when loading the init so we can increase our startup time.

   You can load a module at any time by calling ~emacs-init-load-module-<name>~.

   For example, if I'm going to work with python I just have to call

   : M-x emacs-init-load-module-python-eglot

   You can use =config.el= to automatically load modules you always use:

#+begin_src elisp
;; file: ~/.config/emacs_init/config.el
(emacs-init-load-module-python-eglot)
#+end_src

** More
   Contact me if you want anything and I'll try to help :)
